version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./config/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - nginx-net
    ports:
      - 9090:9090
    deploy:
      labels:
       - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
       - "traefik.http.routers.prometheus.service=prometheus"
       - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
       - "traefik.docker.network=nginx-net"
      placement:
        constraints:
        - node.role==manager
      restart_policy:
        condition: on-failure

networks:
  nginx-net:
    external:
      name: nginx-net