#Using Version 2 of Docker compose from this documentation: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Docker-Compose
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/conf.d/umami.conf:/etc/nginx/conf.d/umami.conf:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.2.1
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-net
    environment:
     - DEFAULT_EMAIL=miw023@ucsd.edu 
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: 1234567890
    depends_on:
      - db
    restart: always
    networks:
      - nginx-net
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - nginx-net
volumes:
  umami-db-data:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  nginx-net:
    external:
      name: nginx-net
